export const products = [
  {
    id: 1,
    title: "Cappadocia",
    author: "ELeonora",
    price: 40000,
    stock: 12,
    description: "Cappadocia",
    category: "Fotografia",
    img: "https://res.cloudinary.com/dkcs0lbjf/image/upload/v1712234370/samples/balloons.jpg",
  },
  {
    id: 2,
    title: "Sabana Africana",
    author: "ELeonora",
    price: 26000,
    stock: 12,
    description: "Sabana Africana",
    category: "Animales",
    img: "https://res.cloudinary.com/dkcs0lbjf/video/upload/v1712234361/samples/elephants.jpg",
  },
  {
    id: 3,
    title: "Breakfast",
    author: "ELeonora",
    price: 23400,
    stock: 12,
    description: "Breakfast",
    category: "Fotografia",
    img: "https://res.cloudinary.com/dkcs0lbjf/image/upload/v1712234371/samples/breakfast.jpg",
  },
  {
    id: 4,
    title: "Bosque",
    author: "Juan Ventura",
    price: 35000,
    stock: 12,
    description: "Bosque",
    category: "Paisaje",
    img: "https://res.cloudinary.com/dkcs0lbjf/image/upload/v1712234356/samples/landscapes/nature-mountains.jpg",
  },
  {
    id: 5,
    title: "Montaña",
    author: "Juan Ventura",
    price: 64000,
    stock: 12,
    description: "Montaña",
    category: "Paisaje",
    img: "https://res.cloudinary.com/dkcs0lbjf/image/upload/v1712234358/samples/landscapes/landscape-panorama.jpg",
  },
  {
    id: 6,
    title: "Pigmentos",
    author: "Juan Ventura",
    price: 12800,
    stock: 12,
    description: "Pigmentos",
    category: "Fotografia",
    img: "https://res.cloudinary.com/dkcs0lbjf/image/upload/v1712234355/samples/food/spices.jpg",
  },
  {
    id: 7,
    title: "Perros",
    author: "Juan Ventura",
    price: 35000,
    stock: 12,
    description: "Perros",
    category: "Animales",
    img: "https://res.cloudinary.com/dkcs0lbjf/image/upload/v1712234351/samples/animals/three-dogs.jpg",
  },
  {
    id: 8,
    title: "New York",
    author: "Vera Rod",
    price: 45000,
    stock: 12,
    description: "New York",
    category: "Fotografia",
    img: "https://res.cloudinary.com/dkcs0lbjf/image/upload/v1712234352/samples/landscapes/architecture-signs.jpg",
  },
  {
    id: 9,
    title: "Reno",
    author: "Vera Rod",
    price: 28000,
    stock: 12,
    description: "Reno",
    category: "Fotografia",
    img: "https://res.cloudinary.com/dkcs0lbjf/image/upload/v1712234346/samples/animals/reindeer.jpg",
  },
  {
    id: 10,
    title: "Mar",
    author: "Vera Rod",
    price: 12800,
    stock: 12,
    description: "Mar",
    category: "Fotografia",
    img: "https://res.cloudinary.com/dkcs0lbjf/image/upload/v1712234353/samples/landscapes/beach-boat.jpg",
  },
  {
    id: 11,
    title: "Azul y Rojo",
    author: "Victor Costa",
    price: 35000,
    stock: 12,
    description: "Arte abstracto con líneas expresivas y colores contrastantes",
    category: "Abstracto",
    img: "https://res.cloudinary.com/dkcs0lbjf/image/upload/v1713893619/vitor_costa_5_vgumda.jpg",
  },
  {
    id: 12,
    title: "Lineas y Circulos",
    author: "Victor Costa",
    price: 38000,
    stock: 12,
    description: "Arte geométrico con líneas y círculos",
    category: "Abstracto",
    img: "https://res.cloudinary.com/dkcs0lbjf/image/upload/v1713893617/vitor_costa_6_chkrdr.jpg",
  },
  {
    id: 13,
    title: "Lineas y Circulos II",
    author: "Victor Costa",
    price: 38000,
    stock: 12,
    description: "Arte geométrico con líneas y círculos",
    category: "Abstracto",
    img: "https://res.cloudinary.com/dkcs0lbjf/image/upload/v1713893617/vitor_costa_2_ekknrq.jpg",
  },
  {
    id: 14,
    title: "Formas Abstractas II",
    author: "Victor Costa",
    price: 38000,
    stock: 12,
    description: "Arte abstracto con trazos minimalistas",
    category: "Abstracto",
    img: "https://res.cloudinary.com/dkcs0lbjf/image/upload/v1713893617/vitor_costa_fnydq5.jpg",
  },
  {
    id: 15,
    title: "Formas Abstractas III",
    author: "Victor Costa",
    price: 39000,
    stock: 12,
    description: "Arte abstracto con trazos minimalistas",
    category: "Abstracto",
    img: "https://res.cloudinary.com/dkcs0lbjf/image/upload/v1713893617/vitor_costa_4_maawb2.jpg",
  },
  {
    id: 16,
    title: "Lineas y Circulos III",
    author: "Victor Costa",
    price: 38000,
    stock: 12,
    description: "Arte geométrico con líneas y círculos",
    category: "Abstracto",
    img: "https://res.cloudinary.com/dkcs0lbjf/image/upload/v1713893616/vitor_costa_3_dk4w5w.jpg",
  },
  {
    id: 17,
    title: "Baño nocturno",
    author: "Caro de la Hoz",
    price: 22900,
    stock: 12,
    description:
      "Ilustración infantil digital. Perro salchicha disfrutando de un relajante baño nocturno.",
    category: "Infantil",
    img: "https://res.cloudinary.com/dkcs0lbjf/image/upload/v1713911448/caro_de_la_hoz_wdgonw.jpg",
  },
  {
    id: 18,
    title: "Frida retrato",
    author: "Dina Boland",
    price: 36300,
    stock: 12,
    description:
      "Todos los personajes conviven en un maravilloso libro que los transporta a traves de un bosque oscuro y luminoso a la vez.¿Hacia donde van? ¿Quien los espera? El viaje continúa, próxima parada: nuestra imaginación",
    category: "Infantil",
    img: "https://res.cloudinary.com/dkcs0lbjf/image/upload/v1713911817/dina_boland_flwzu7.jpg",
  },
  {
    id: 19,
    title: "Una Flor",
    author: "Roactis",
    price: 32400,
    stock: 12,
    description: "Geometria de la naturaleza, módulos que componen una flor",
    category: "Infantil",
    img: "https://res.cloudinary.com/dkcs0lbjf/image/upload/v1713912044/roactis2_q9sn0a.jpg",
  },
  {
    id: 20,
    title: "Luna Nueva",
    author: "Roactis",
    price: 32400,
    stock: 12,
    description: "Serie Las edades de la Luna, creada en acrílico y stamping",
    category: "Infantil",
    img: "https://res.cloudinary.com/dkcs0lbjf/image/upload/v1713912044/roactis3_ku1xyx.jpg",
  },
  {
    id: 21,
    title: "Jungle",
    author: "Den Alicia",
    price: 32400,
    stock: 12,
    description: "Jungle print - Ilustración digital.",
    category: "Pop Art",
    img: "https://res.cloudinary.com/dkcs0lbjf/image/upload/v1713912791/den_alicia_xiuzue.jpg",
  },
  {
    id: 22,
    title: "Doodles",
    author: "Den Alicia",
    price: 32400,
    stock: 12,
    description: "Doodles - Ilustración digital.",
    category: "Pop Art",
    img: "https://res.cloudinary.com/dkcs0lbjf/image/upload/v1713912791/den_alicia_2_qacqn9.jpg",
  },
  {
    id: 23,
    title: "Jungle II",
    author: "Den Alicia",
    price: 32400,
    stock: 12,
    description: "Jungle print - Ilustración digital.",
    category: "Pop Art",
    img: "https://res.cloudinary.com/dkcs0lbjf/image/upload/v1713912807/den_alicia_3_k2y69z.jpg",
  },
  {
    id: 24,
    title: "Amor",
    author: "Den Alicia",
    price: 32400,
    stock: 12,
    description: "Amor propio. Ilustración digital",
    category: "Pop Art",
    img: "https://res.cloudinary.com/dkcs0lbjf/image/upload/v1713912808/den_alicia_5_cbpxqz.png",
  },
  {
    id: 25,
    title: "Boca",
    author: "Den Alicia",
    price: 32400,
    stock: 12,
    description: "Boca. Ilustracion Digital",
    category: "Pop Art",
    img: "https://res.cloudinary.com/dkcs0lbjf/image/upload/v1713912807/den_alicia_4_uvhuvp.png",
  },
  {
    id: 26,
    title: "Bananas",
    author: "Den Alicia",
    price: 32400,
    stock: 12,
    description: "Bananas",
    category: "Pop Art",
    img: "https://res.cloudinary.com/dkcs0lbjf/image/upload/v1713912823/den_alicia_6_flpwqm.jpg",
  },
  {
    id: 27,
    title: "Magic Can",
    author: "Den Alicia",
    price: 36300,
    stock: 12,
    description: "MAGIC CAN - Ilustración digital",
    category: "Pop Art",
    img: "https://res.cloudinary.com/dkcs0lbjf/image/upload/v1713912791/den_alicia_7_glyeho.jpg",
  },
];
